version: '3.8'

services:
  mysql: # See Also: https://hub.docker.com/_/mysql
    image: mysql:8.0.31
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classting
      MYSQL_USER: classting
      MYSQL_PASSWORD: classting
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      # - ./sql:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      args:
        PORT: 8080
    environment:
      DEFAULT_DB_NAME: classting
      DEFAULT_DB_USER: classting
      DEFAULT_DB_PASSWORD: classting
      DEFAULT_DB_HOST: "mysql"
      DEFAULT_DB_PORT: 3306
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 8080:8080
    command: |
      sh -c "./wait-for-it.sh -t 30 mysql:3306 --
        npm run start:dev"

volumes:
  mysql:
